version: '2'
volumes:
  pg_data:
services:
  api:
    build: ./api
    working_dir: /src/
    ports:
      - "8080:8080"
    volumes:
      - "./api:/src/"
      - "/src/node_modules"
    command: "/bin/sh -c 'npm install && node index.js'"
    environment:
      - STEAM_ACCOUNT
      - STEAM_PASSWORD
  discord:
    build: ./discord
    working_dir: /src/
    volumes:
      - "./discord:/src/"
      - "/src/node_modules"
    command: "/bin/sh -c 'npm install && node index.js'"
    environment:
      - DISCORD_SECRET
